version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: strnadiapi-app
    ports: 
      - "6789:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file: .env
    networks: 
      - app_network
  db:
    image: postgres:17
    container_name: strnadiapi-db
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /home/poproshaikin/strnadiapi-db:/var/lib/postgresql/data
    networks: 
      - app_network
networks:
  app_network:
    driver: bridge